name: bunny_upload_function
description: "Appwrite function to upload files to Bunny storage for XapZap."
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # No extra deps needed; we use dart:io + dart:convert

